document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '  <meta charset=\"UTF-8\" />\n' );
document.write( '  <title>PatchSearch</title>\n' );
document.write( '  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n' );
document.write( '  <style>\n' );
document.write( '    body {\n' );
document.write( '      margin: 0;\n' );
document.write( '      font-family: \'Comic Sans MS\', cursive, sans-serif;\n' );
document.write( '      background: linear-gradient(135deg, #fefcea, #f1daff);\n' );
document.write( '      display: flex;\n' );
document.write( '      flex-direction: column;\n' );
document.write( '      align-items: center;\n' );
document.write( '      justify-content: center;\n' );
document.write( '      min-height: 100vh;\n' );
document.write( '      overflow-x: hidden;\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    header {\n' );
document.write( '      text-align: center;\n' );
document.write( '      margin-bottom: 2rem;\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    h1 {\n' );
document.write( '      font-size: 3rem;\n' );
document.write( '      color: #333;\n' );
document.write( '      text-shadow: 2px 2px #ffccff;\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    .search-box {\n' );
document.write( '      background: #ffffff;\n' );
document.write( '      border: 4px dashed #ff99cc;\n' );
document.write( '      border-radius: 20px;\n' );
document.write( '      padding: 2rem;\n' );
document.write( '      width: 90%;\n' );
document.write( '      max-width: 800px;\n' );
document.write( '      box-shadow: 0 8px 16px rgba(0,0,0,0.1);\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    iframe {\n' );
document.write( '      width: 100%;\n' );
document.write( '      height: 600px;\n' );
document.write( '      border: none;\n' );
document.write( '      border-radius: 12px;\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    footer {\n' );
document.write( '      margin-top: 2rem;\n' );
document.write( '      text-align: center;\n' );
document.write( '      font-size: 0.9rem;\n' );
document.write( '      color: #666;\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    #credit {\n' );
document.write( '      margin-top: 0.5rem;\n' );
document.write( '      font-size: 0.9rem;\n' );
document.write( '      color: #444;\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    @media (max-width: 600px) {\n' );
document.write( '      h1 {\n' );
document.write( '        font-size: 2.2rem;\n' );
document.write( '      }\n' );
document.write( '      .search-box {\n' );
document.write( '        padding: 1rem;\n' );
document.write( '      }\n' );
document.write( '      iframe {\n' );
document.write( '        height: 500px;\n' );
document.write( '      }\n' );
document.write( '    }\n' );
document.write( '  </style>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '  <header>\n' );
document.write( '    <h1>🌈 PatchSearch</h1>\n' );
document.write( '    <p><em>Your AI-powered playground for curiosity</em></p>\n' );
document.write( '  </header>\n' );
document.write( '\n' );
document.write( '  <div class=\"search-box\">\n' );
document.write( '    <h2 style=\"text-align:center;\">Ask Me Anything 👇</h2>\n' );
document.write( '    <div id=\"deployment-0e2e26e8-4dc4-40ed-b8a0-8a5276dce1d1\"></div>\n' );
document.write( '    <script src=\"https://studio.pickaxe.co/api/embed/bundle.js\" defer></script>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '  <footer>\n' );
document.write( '    <p>Made with ❤️ by Liam | Comic Sans forever</p>\n' );
document.write( '    <p id=\"credit\"></p>\n' );
document.write( '    <script>\n' );
document.write( '      const text = \"🛠️ Made with VS Code & Copilot\";\n' );
document.write( '      let i = 0;\n' );
document.write( '      const speed = 50;\n' );
document.write( '      function typeWriter() {\n' );
document.write( '        if (i < text.length) {\n' );
document.write( '          document.getElementById(\"credit\").innerHTML += text.charAt(i);\n' );
document.write( '          i++;\n' );
document.write( '          setTimeout(typeWriter, speed);\n' );
document.write( '        }\n' );
document.write( '      }\n' );
document.write( '      typeWriter();\n' );
document.write( '    </script>\n' );
document.write( '  </footer>\n' );
document.write( '</body>\n' );
document.write( '</html>\n' );
